apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
spec:
  replicas: 2 # One pod will be killed when there is no load by HPA
  selector:
    matchLabels:
      app: app-frontend
  strategy:
    type: Recreate # All existing Pods are killed before new ones are created
  template:
    metadata:
      labels:
        app: app-frontend
        role: frontend
    spec:
      containers:
        - name: app-frontend
          image: 108782093326.dkr.ecr.us-east-1.amazonaws.com/group1/frontend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3001
          envFrom:
            - configMapRef:
                name: app-frontend-config
          resources:
            limits:
              memory: "400Mi"
              cpu: 0.5
            requests:
              memory: "300Mi"
              cpu: 0.25 # gives 1/2 of the limit